apiVersion: v1
kind: ReplicationControllerList
metadata:
  name: geth-nodes
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: node-geth-422
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            type: node
            vendor: geth
            version: "4.2.2"
        spec:
          containers:
            - name: node
              image: "etcdev/fork-geth:latest"
              imagePullPolicy: Always
              ports:
                - name: rpc
                  containerPort: 8545
                - name: p2p
                  hostPort: 30303
                  containerPort: 30303
                  protocol: TCP
                - name: p2p-udp
                  hostPort: 30303
                  containerPort: 30303
                  protocol: UDP
              env:
                - name: VERSION
                  value: "4.2.2"
              volumeMounts:
                - mountPath: /data
                  name: blockchain
          volumes:
            - name: blockchain
              gcePersistentDisk:
                pdName: geth-422
                fsType: ext4
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: node-geth-500
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            type: node
            vendor: geth
            version: "5.0.0"
        spec:
          containers:
            - name: node
              image: "etcdev/fork-geth:latest"
              imagePullPolicy: Always
              ports:
                - name: rpc
                  containerPort: 8545
                - name: p2p
                  hostPort: 30303
                  containerPort: 30303
                  protocol: TCP
                - name: p2p-udp
                  hostPort: 30303
                  containerPort: 30303
                  protocol: UDP
              env:
                - name: VERSION
                  value: "5.0.0"
              volumeMounts:
                - mountPath: /data
                  name: blockchain
          volumes:
            - name: blockchain
              gcePersistentDisk:
                pdName: geth-500
                fsType: ext4
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: node-geth-530
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            type: node
            vendor: geth
            version: "5.3.0"
        spec:
          containers:
            - name: node
              image: "etcdev/fork-geth:latest"
              imagePullPolicy: Always
              ports:
                - name: rpc
                  containerPort: 8545
                - name: p2p
                  hostPort: 30303
                  containerPort: 30303
                  protocol: TCP
                - name: p2p-udp
                  hostPort: 30303
                  containerPort: 30303
                  protocol: UDP
              env:
                - name: VERSION
                  value: "5.3.0"
              volumeMounts:
                - mountPath: /data
                  name: blockchain
          volumes:
            - name: blockchain
              gcePersistentDisk:
                pdName: geth-530
                fsType: ext4