apiVersion: v1
kind: ServiceList
metadata:
  name: nodes-services
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: geth-422-svc
    spec:
      ports:
      - name: rpc
        port: 8545
      selector:
        vendor: geth
        version: "4.2.2"
  - apiVersion: v1
    kind: Service
    metadata:
      name: geth-500-svc
    spec:
      ports:
      - name: rpc
        port: 8545
      selector:
        vendor: geth
        version: "5.0.0"
  - apiVersion: v1
    kind: Service
    metadata:
      name: geth-530-svc
    spec:
      ports:
      - name: rpc
        port: 8545
      selector:
        vendor: geth
        version: "5.3.0"


  - apiVersion: v1
    kind: Service
    metadata:
      name: parity-192-svc
    spec:
      ports:
      - name: rpc
        port: 8545
      selector:
        vendor: parity
        version: "1.9.2"
  - apiVersion: v1
    kind: Service
    metadata:
      name: parity-193-svc
    spec:
      ports:
      - name: rpc
        port: 8545
      selector:
        vendor: parity
        version: "1.9.3"
  - apiVersion: v1
    kind: Service
    metadata:
      name: parity-197-svc
    spec:
      ports:
      - name: rpc
        port: 8545
      selector:
        vendor: parity
        version: "1.9.7"
  - apiVersion: v1
    kind: Service
    metadata:
      name: parity-1104-svc
    spec:
      ports:
      - name: rpc
        port: 8545
      selector:
        vendor: parity
        version: "1.10.4"