apiVersion: v1
kind: ReplicationControllerList
metadata:
  name: parity-nodes
items:
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: node-parity-192
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            type: node
            vendor: parity
            version: "1.9.2"
        spec:
          containers:
            - name: node
              image: "etcdev/fork-parity:latest"
              ports:
                - name: rpc
                  containerPort: 8545
                - name: p2p
                  hostPort: 30303
                  containerPort: 30303
                  protocol: TCP
                - name: p2p-udp
                  hostPort: 30303
                  containerPort: 30303
                  protocol: UDP
              env:
                - name: VERSION
                  value: "1.9.2"
              volumeMounts:
                - mountPath: /data
                  name: blockchain
          volumes:
            - name: blockchain
              gcePersistentDisk:
                pdName: parity-192
                fsType: ext4
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: node-parity-193
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            type: node
            vendor: parity
            version: "1.9.3"
        spec:
          containers:
            - name: node
              image: "etcdev/fork-parity:latest"
              ports:
                - name: rpc
                  containerPort: 8545
                - name: p2p
                  hostPort: 30303
                  containerPort: 30303
                  protocol: TCP
                - name: p2p-udp
                  hostPort: 30303
                  containerPort: 30303
                  protocol: UDP
              env:
                - name: VERSION
                  value: "1.9.3"
              volumeMounts:
                - mountPath: /data
                  name: blockchain
          volumes:
            - name: blockchain
              gcePersistentDisk:
                pdName: parity-193
                fsType: ext4
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: node-parity-197
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            type: node
            vendor: parity
            version: "1.9.7"
        spec:
          containers:
            - name: node
              image: "etcdev/fork-parity:latest"
              ports:
                - name: rpc
                  containerPort: 8545
                - name: p2p
                  hostPort: 30303
                  containerPort: 30303
                  protocol: TCP
                - name: p2p-udp
                  hostPort: 30303
                  containerPort: 30303
                  protocol: UDP
              env:
                - name: VERSION
                  value: "1.9.7"
              volumeMounts:
                - mountPath: /data
                  name: blockchain
          volumes:
            - name: blockchain
              gcePersistentDisk:
                pdName: parity-197
                fsType: ext4
  - kind: ReplicationController
    apiVersion: v1
    metadata:
      name: node-parity-1104
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            type: node
            vendor: parity
            version: "1.10.4"
        spec:
          containers:
            - name: node
              image: "etcdev/fork-parity:latest"
              ports:
                - name: rpc
                  containerPort: 8545
                - name: p2p
                  hostPort: 30303
                  containerPort: 30303
                  protocol: TCP
                - name: p2p-udp
                  hostPort: 30303
                  containerPort: 30303
                  protocol: UDP
              env:
                - name: VERSION
                  value: "1.10.4"
              volumeMounts:
                - mountPath: /data
                  name: blockchain
          volumes:
            - name: blockchain
              gcePersistentDisk:
                pdName: parity-1104
                fsType: ext4