apiVersion: v1
kind: ServiceList
metadata:
  name: frontend-service
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: front
    spec:
      ports:
        - port: 80
          name: http
      selector:
        name: frontend
      type: LoadBalancer
      loadBalancerIP: "35.225.108.59"