kind: ReplicationController
apiVersion: v1
metadata:
  name: status
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: front
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
          livenessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Host
                  value: fork.etcdevteam.com
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
        - name: checker
          image: "etcdev/fork-status:latest"
          volumeMounts:
            - name: shared-data
              mountPath: /pod-data
